### ISSUE TITLE
Read lenght error

### ISSUE THREAD

**Issue by jregalad** [linsalrob/qudaich#1]
I'm getting the following read length error:
Current version of qudaich can not process sequence length > 2000

But I'm using Illumina read data in fastq format with maximum read length of 142

Commands I used:
qudaich_search_db -q <myreads1> -d <myreads2> -p n -f freq.txt
qudaich_alignment -f freq.txt -o test.out

"myreads#" are gzip compressed

**Comment by jregalad** [comment]
I solved the issue by converting my read data from fastq to fasta format. Are there any plans to incorporate read quality into the quadaich pipeline?

**Comment by jregalad** [comment]
If I use gzip compressed data, again, I get: 
Current version of qudaich can not process sequence length > 2000

regardless of the format (fastq or fasta)

**Comment by linsalrob** [comment]
We currently don't support fastq or gz. Working on adding that soon.
