### ISSUE TITLE
error w/install - make all error 

### ISSUE THREAD

**Issue by jbholm** [linsalrob/qudaich#3]
Hi, 
I've tried to install this and get errors as per below, something with an omp.h file, it seems: 

make -C /qudaich/src/
g++ -c -O3 -Wall -Wno-char-subscripts -Wno-unused-but-set-variable -Wno-maybe-uninitialized -Wno-unused-variable -Wno-unused-variable search_db_hypo1_dna_dna.cpp
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
search_db_hypo1_dna_dna.cpp:43:10: fatal error: 'omp.h' file not found
# include <omp.h>

```
     ^
```

2 warnings and 1 error generated.
make: **\* [search_db_hypo1_dna_dna.o] Error 1

---

any help is appreciated!

**Comment by jregalad** [comment]
Your c++ compiler can't find the OpenMP headers. Do you have OpenMP installed?

**Comment by jbholm** [comment]
I don't think so!

**Comment by jbholm** [comment]
Thank you - this resolved that problem. I now have this error after make all: 

src/run_search_db.cpp: In function ‘int main(int, char*_)’:
src/run_search_db.cpp:181:66: error: expected ‘)’ before ‘{’ token
make: *_\* [qudaich_search_db] Error 1

**Comment by jregalad** [comment]
That's weird, what system are you using and what version of gcc do you have. I tried reinstalling in my system and now I get the same error. We'll have to wait for the developers to answer.

**Comment by jbholm** [comment]
I'm using Linux Red Hat, gcc4.7.2

**Comment by jregalad** [comment]
I've tried in ubuntu 16 (gcc 5.3.1) and ubuntu 14 (4.8.4) with the same error. 
Some bug was introduced in run_search_db.cpp with commit message "correcting a -t for top" seven days ago. We'll have to wait for the developers. 
If you don't mind I can send you my functional binaries. I promise not to send any virus :)

**Comment by jbholm** [comment]
No thank you - I'm still new to this all so I am not sure what I would do with those anyways :) I'll wait to hear from the developers.

**Comment by linsalrob** [comment]
Apologies, I inadvertently introduced an extra bracket. This has been fixed. Please use

`git pull
`
and then

```
make clean
make all
```

to rebuild the software.

**Comment by jbholm** [comment]
Thank you, that worked! I'm trying to run qudaich_search_db but now get a Segmentation Fault error. Not sure if this is actually qudaich-related, but I've never gotten this error before. script below:

qudaich_search_db -q /local/scratch-hs/romero3/TERM/idba_assemblies_TERM/contigs.fa -d /local/scratch-hs/romero3/pcoa3/idba_assemblies_no_term/contigs.fa -p

**Comment by jbholm** [comment]
Thanks - all set!!

**Comment by linsalrob** [comment]
Did you solve the segfault error?

Rob

**Comment by jbholm** [comment]
Yes! Thank you. I uninstalled entirely and reinstalled.  

One more question: any way to increase limit of sequences? I got an error saying maximum of 2 billion sequences.

**Comment by linsalrob** [comment]
I will work on that, but I am not sure at the moment. I"ll start a new
issue on github so I can track it.

Let me know how you get on!

Rob
