### ISSUE TITLE
RFC: alignment of sequences > 2000

### ISSUE THREAD

**Issue by burgerm** [linsalrob/qudaich#5]
Do you plan to improve your software package so it will be able to align sequences to a fasta file with sequences which consists of more then 2000 bps?

Your software seems very promising for replacing blastn of the blast+ package but this 'feature' is a nogo for using the ncbi nt database as reference.

Additionally, your instruction for installing the software from source by using '% make all' didn't work for me. Simply issuing 'make' did the trick.

kind regards.

Marcel Burger

**Comment by linsalrob** [comment]
Hi Marcel

We do not have plans to increase the alignment length at the moment, though it would be an interesting CS challenge.

I am not sure why make all did not work for you (did you include the % - you should not do so). 

Thanks for the comments.

Rob
